const asyncHelp = function() {
    return new Promise((resolve,reject) => {
        const randomVal = Math.floor(Math.random() *10);
        setTimeout(() => {
            console.log('Doing...'+randomVal)
            if(randomVal > 3) {
                reject("Error in "+randomVal)
            } else {
                resolve("Done in "+randomVal);
            }
        }, randomVal*1000);
    })
};
const asyncTask = [asyncHelp, asyncHelp, asyncHelp, asyncHelp, asyncHelp];

const executeInSequence = async (asyncTask) => {
        let result = [];
        for(let i=0;i<asyncTask.length;i++) {
            try {
                const res = await asyncTask[i]();
                result.push(res); 
            } catch(err) {
                result.push(err); 
            }
        }
        return result;
};

executeInSequence(asyncTask).then((val) => console.log(val)).catch((err) => console.log("Main error "+ err));
